### ISSUE TITLE
are you going to add more Macintosh computers?

### ISSUE THREAD

**Issue by 12d3** [zydeco/minivmac4ios#11]
if so add add a computer that supports Mac systems all the way up to Mac OS 8.1

**Comment by zydeco** [comment]
Mac OS 8.1 requires a 68040 CPU (or a 68030 with some hacking), which I think is out of the scope of Mini vMac any time soon.

Mini vMac can emulate several Macintosh computers with 68000 CPUs, and the Macintosh II, that has a 68020, but I have only included 128K, Plus and Mac II with 640×480 and 1024×768 8-bit resolutions in the default build, since the others aren't too different, and each variant adds about 500K to the size.
