### ISSUE TITLE
Possible to add nearest neighbor interpolation?

### ISSUE THREAD

**Issue by vaporstack** [zydeco/minivmac4ios#23]
Not sure if this is possible.  The variants of mini vmac I've built for desktop render using OpenGL which has nearest neighbor options for rescaling - my cursory digging suggested that CGImageCreate already has a parameter to disable interpolation which is set to false already, so I suspect that the interpolation happens somewhere in the CoreGraphics drawing stack that I can't find.

I'm a sucker for clean pixels :)

Many thanks for your work on this.,

**Comment by zydeco** [comment]
I've implemented an option in settings that lets you choose between Nearest, Linear and Trilinear (they're the available options for a `CALayer`'s `magnificationFilter` and `minificationFilter`)

I've also added some other related features:
 * The scale will be rounded to 1.0 if it is close enough (for example, iPhone 6 or X in landscape).
 * When the scale is an integer, it will always use nearest neighbour interpolation.

This probably won't work as expected on an iPhone Plus, since the native screen scale isn't an integer, I'll check it when I can borrow one.
