### ISSUE TITLE
Add missing speed control options

### ISSUE THREAD

**Issue by adespoton** [zydeco/minivmac4ios#3]
Missing options are:
16x, 32x, all-out

[edit] also, Stopped toggle (pause), run in background toggle, and autoslow.

**Comment by zydeco** [comment]
I didn't add the faster speed options because setting the speed faster than something your device can handle will lock up the UI, since everything is run on the main thread, so you can't turn it back without force quitting the app. The same thing happens on the OSX version too (notable when running FPU-heavy things on the Mac II), so I guess it's fine to add, since the speed value doesn't persist across relaunches.

**Comment by adespoton** [comment]
I noticed it looks like you have autoslow hardcoded to enabled.  Is stopped toggle or background dependent on how iOS handles the main thread?
