### ISSUE TITLE
Bundles for each supported computer?

### ISSUE THREAD

**Issue by gingerbeardman** [zydeco/minivmac4ios#40]
It would be great if there were bundles incuded for each supported computer, as there aren't that many.

Users could then configure each for RAM and screen dimensions. 

If too many bundles are an issue then perhaps only a few could be added as Frameworks to the final build phase, with the rest being omitted.

I could help with this if required.

**Comment by zydeco** [comment]
Due to the way Mini vMac works, RAM and screen size can only be set at compile time, so each bundle is a copy of the Mini vMac emulator compiled with a different configuration.
I only included bundles for the 128K, Plus and Mac II with two screen sizes, since I thought those were the most representative, and should be enough to run all software that can run in Mini vMac (SE and Classic should be the same as the Plus in terms of software capability).
Feel free to make a pull request adding more machines or screen sizes if you think it's useful, just don't add one for every possible iPhone/iPad screen size 😅

**Comment by gingerbeardman** [comment]
Sure thing!

I'll see how I get on. The only reason I wanted Classic is that's what I have IRL, there are some subtle differences between that and Plus in how it runs my software setup.

**Comment by gingerbeardman** [comment]
I won't get around to doing this because I'm all about Basilisk iOS!
