### ISSUE TITLE
Cmd-key shortcuts break in iPadOS 16.3

### ISSUE THREAD

**Issue by crutch-meef** [zydeco/minivmac4ios#45]
Hi, love running this on my iPad and using it for software development daily:  https://68kmla.org/bb/index.php?threads/adjusting-sound-volume-with-keyboard-shortcuts-on-68k-macs.43221/#post-471713

Have a problem since the latest software update though:  the iPad now appears to be stealing many Cmd-key combinations (this always happened with Cmd-Q but now appears to also intercept Cmd-F, Cmd-G, and most troubling Cmd-W) so vintage apps running under Mini vMac can't see them.

This makes Mini vMac much less useful because (for example) Cmd-F is "Find" and Cmd-G is "Find Again" in many apps ... most troublingly, Cmd-W is now a global shortcut to instantly exit an app, totally killing the emulator when I am just trying to close a window (and of course, not saving anything).  It appears to be possible for some iOS apps to override this behavior (Safari uses Cmd-W just to close a tab, for example).  
Is it possible for Mini vMac to prevent iPadOS from grabbing these keypresses?

Thanks for the great work on this terrific tool!

**Comment by zydeco** [comment]
Hi!
Thanks for reporting this! 
I think I've fixed it in as much as I could in https://github.com/zydeco/minivmac4ios/commit/ceb0813eee7709fa1a085c96f678c6df6e27f01d:
* ⌘-w and most others will get passed to the emulated machine if it's running
* ⌘-q and ⌘-h don't seem interceptable, the app doesn't receive any key events for them, but ⌘-q doesn't do anything but ⌘-h will take you to the home screen

**Comment by appscaptain** [comment]
I'd say that cmd-h is possible to live more without, however cmd-w and cmd-q is used constantly. It is really a pain having to manually click on GUI elements as a long time macOS user. The key short shortcuts sit in the fingers so it's very hard not to use them. I hope there is some workaround. I am on 16.4.1. on an iPad gen 6. I can confirm I constantly close the whole emulator with cmd-w (a unhealthy shutdown) by accident because I use it to close every window, making it very hard to use it productively.
