### ISSUE TITLE
Feature: Add optional iOS predictive typing/capitalization

### ISSUE THREAD

**Issue by adespoton** [zydeco/minivmac4ios#7]
All in the subject line :)

I have to admit though; I haven't examined how you implemented your keyboard, so feel free to just close this issue if it's not reasonably straightforward to implement.

**Comment by zydeco** [comment]
The keyboard is just a view custom buttons, since it's the easiest way to support sending key up/down events and have all the keys from a mac keyboard.

The iOS on-screen keyboard is made for text editing, so it doesn't send key down/up events, only text, and while mapping this to mac scancodes is sometimes possible, some characters cannot be entered with the keyboard on a Mac Plus, it would depend on the language and keyboard layout of the emulated machine), and you wouldn't be able to hold a key down.
